language: ruby
rvm:
- 2.3.3

cache:
    yarn: true

install:
    - . $HOME/.nvm/nvm.sh
    - nvm install 8
    - nvm use 8
    - npm install -g yarn

script: bash ./bin/automated

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
