language: ruby
rvm:
  - 2.3.3

services:
  - docker

sudo: required

cache:
    yarn: true

install:
    - . $HOME/.nvm/nvm.sh
    - nvm install 8
    - nvm use 8
    - npm install -g yarn

script: bash ./bin/automated

deploy:
  - provider: script
    script: ./bin/deploy

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
