
# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "source{d} tech talks"
email: "talks@sourced.tech"
description: "source{d} tech talks"
baseurl: ""
url: "http://talks.sourced.tech"
googleAnalyticsTrackingId: "UA-69608223-4"
googleAnalyticsSiteUrl: "talks.sourced.tech"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "source{d}"
organizerAlternateName: "source{d} tech talks"
organizerDescription: "source{d} tech talks is a one-day conference"
organizerEmail: "talks@sourced.tech"
organizerLogo: "http://sourced.tech/img/logos/logo-blue.svg"
organizerLink: "http://sourced.tech/"

# Head
metaKeywords: "event, talks, tech, srcd, devops, sourced, developers, madrid"
twitterAccount: "@srcd_"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png?v=2"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png?v=2"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png?v=2"

# Footer
socialLinks:
 - {link: "https://github.com/src-d/", icon: "github"}
 - {link: "https://twitter.com/srcd_", icon: "twitter"}
 - {link: "https://www.linkedin.com/company/10284920/", icon: "linkedin"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://sourced.tech/", text: "sourced{d}"}
   - {link: "https://blog.sourced.tech/", text: "blog"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:talks@sourced.tech", text: "talks@sourced.tech"}

collections:
  current_talks:
    output: false
  past_talks:
    output: false
